<?php
/**
 * Created by PhpStorm.
 * User: Anuradha Sanjeewa
 * Date: 11/11/2015
 * Time: 17:59
 */
?>
<?php
/**
 * Created by PhpStorm.
 * User: Anuradha Sanjeewa
 * Date: 11/11/2015
 * Time: 17:38
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php require dirname(__FILE__) . '/../../headers.php'; ?>
</head>
<body>
<?php
require dirname(__FILE__) . '/../../loader.php';
require dirname(__FILE__) . '/../../navbar.php';
require dirname(__FILE__) . '/../../audio.php';
require dirname(__FILE__) . '/../../bkgimg.php';
?>

<div class="container">
    <div class="well" style="margin-top: 40px ;background-color: rgba(245, 245, 245, 0.8); height: 100%">
        <p style="font-size: 2em" class="text-center">General Game Information</p>
    </div>
    <div class=" well col-sm-12" style="font-size: 12pt; background-color: rgba(245, 245, 245, 0.8);">
        <h3 class="text-center">
            Game Information...
        </h3>
        <hr>
        <strong>Game starting</strong>

        <p>
            Once the game starts the server will communicate the game board and other details. The tanks are required to
            move around
            in on the board and attack other tanks. While the game is in play the players can encounter with these
            objects as follows.
        <ol>
            <li>Bricks</li>
            <li>Coins</li>
            <li>Spoils of war</li>
            <li>Life packs</li>
        </ol>
        </p>
        <strong>Bricks</strong>

        <p>
            The bricks can be destroyed by impact or by shooting shells. Once the bricks are destroyed the residue will
            be coins
            which can be collected afterwards.
        </p>
        <strong>Coins</strong>

        <p>
            The coins will appear for a limited time and they can be collected by moving onto the contained cell of the
            board.
        </p>
        <strong>Spoils of war</strong>

        <p>
            These are the coins that are generated by destroying other tanks. These too act as normal coins and can be
            collected similarly.
        </p>
        <strong>Life packs</strong>

        <p>
            Similar to coins these too will appear for a given period of time. Once these are collected the health level
            of the tank by 20%.
        </p>


        <hr>
        <h3 class="text-center">
            Game Rules...
        </h3>
        <hr>
        <ul>
            <li>
                A bullet hit will redue the life of a tank by 10%
            </li>
            <li>
                A player who has health of 0% (or less) will die and drop their coins at the point of death. But they
                will not
                lose the current points. However 25% of the points of the victim will be added to the killer.
            </li>
            <li>
                If a tank hits an obstacle (a standing brick wall or a stone wall), a fixed number of points will be
                deducted
                from the client. The deduction takes place per each turn, thus if a tank keeps hitting an obstacle, it
                will continuously lose
                points
            </li>
            <li>
                If the tank drives in to a water cell, the tank will get destroyed. The coins will not be able to be
                collected by some other tank.
            </li>
            <li>
                Only one movement/ action can be performed per second. All the other commands will be ignored by the
                game server.
            </li>
        </ul>
        <hr>
        <p class="text-center">&copy; NukeIt Games</p>
    </div>
</div>
</body>
</html>

